version: "3.0"
services:
  database:
    image: postgres:9.5.11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: pakjekraam
      POSTGRES_DB: pakjekraam
  web:
    build:
      args:
        - NODE_ENV=development
      context: .
      dockerfile: Dockerfile
    command: dev
    environment:
      - API_MMAPPKEY
      - API_URL
      - APP_ENV=dev
      - APP_NOTIFICATIE_FROM=tester@test.com
      - APP_SECRET=secret
      - DATABASE_URL=pgsql://pakjekraam:insecure@database:5432/pakjekraam
      - IAM_CLIENT_ID=pakjekraam
      - IAM_CLIENT_SECRET=insecure
      - IAM_REALM=pakjekraam
      - IAM_REALM_PUBKEY=
      - IAM_URL=http://keycloak:8081/auth/
      - NODE_ENV=development
      - SWIFT_AUTH_URL=
      - SWIFT_CONTAINER_PREFIX=
      - SWIFT_EXTERNAL_DOMAIN=
      - SWIFT_PROJECT_ID=
      - SWIFT_REGION=
      - SWIFT_TEMP_URL_KEY=
      - SWIFT_USER_DOMAIN_ID=
      - SWIFT_USER_NAME=
      - SWIFT_USER_PASSWORD=
      - THUMBNAILSERVICE_URL=https://thumbnail.service/
    links:
      - database
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./:/srv
      - /srv/node_modules
  keycloak:
    image: jboss/keycloak:6.0.1
    environment:
      DB_ADDR: database
      DB_DATABASE: pakjekraam
      DB_PASSWORD: insecure
      DB_USER: pakjekraam
      DB_VENDOR: postgres
      KEYCLOAK_PASSWORD: insecure
      KEYCLOAK_USER: pakjekraam
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
