version: "3.0"
services:
  database:
    image: postgres:9.5.11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: pakjekraam
      POSTGRES_DB: pakjekraam
  web:
    build:
      args:
        - NODE_ENV=production
      context: .
      dockerfile: Dockerfile
    environment:
      - API_MMAPPKEY
      - API_URL
      - APP_ENV=production
      - APP_NOTIFICATIE_FROM=tester@test.com
      - APP_SECRET=secret
      - DATABASE_URL=pgsql://pakjekraam:insecure@database:5432/pakjekraam
      - NODE_ENV=production
      - SWIFT_AUTH_URL=
      - SWIFT_CONTAINER_PREFIX=
      - SWIFT_EXTERNAL_DOMAIN=
      - SWIFT_PROJECT_ID=
      - SWIFT_REGION=
      - SWIFT_TEMP_URL_KEY=
      - SWIFT_USER_DOMAIN_ID=
      - SWIFT_USER_NAME=
      - SWIFT_USER_PASSWORD=
      - THUMBNAILSERVICE_URL=https://thumbnail.service/
    links:
      - database
